### ISSUE TITLE
Vs Other Similar Languages

### ISSUE THREAD

**Issue by sirinath** [lexi-lambda/hackett#17]
Wondering how you stack against:

 - https://github.com/carp-lang/Carp
 - https://github.com/LuxLang/lux
 - http://typedclojure.org/
 - Typed Racket

What are the advantages and disadvantages?

**Comment by joehillen** [comment]
None of those are pure, Haskell and Hackett are.

**Comment by lexi-lambda** [comment]
Two big things:

  1. Purity and type system features, as @joehillen mentions. TR and core.typed have radically different type systems that are designed to support *gradual typing*, and they attempt to support idiomatic Racket and Clojure, respectively. That comes with a whole host of pros and cons, but one of the biggest missing features is typeclasses, which none of those languages support.

  2. Hackett is also designed to support much more type-level metaprogramming than most other languages, including Haskell. Lux may compare somewhat, due to the way it exposes the compiler to macros, but it doesn’t support hygienic macros, which are pretty important in my experience for being able to write expressive macros.
