### ISSUE TITLE
Scoped type variables

### ISSUE THREAD

**Issue by lexi-lambda** [lexi-lambda/hackett#30]
Hackett should support lexically scoped type variables, a la GHC’s `ScopedTypeVariables` extension. This should be relatively easy to support, due to the way type variables are effectively *already* lexically scoped. One thing that will probably be weird is that type variables and ordinary variables current share a single namespace, so they could shadow ordinary variables.

A simple implementation is probably reasonable to start, and we can see if sharing the same namespace causes any problems.

**Comment by Roxxik** [comment]
I see no problem in them sharing a namespace, it's more of an inconvenience.

I'm not sure on that one, but i think in higher typed languages (thinking of idris or coq) the namespace for term and type variables is the same, because the type system is mandating it. *Some mumbling about dependent types, kinds, universes or some such*
